apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-dashboard
  namespace: metallb-system
spec:
  addresses:
  - 192.168.69.88/32
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-ingress
  namespace: metallb-system
spec:
  addresses:
  - 192.168.69.90/32
  autoAssign: false

