apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app-vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
    - name: dashboard
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden
  namespace: app-vaultwarden
spec:
  entryPoints:
    - web   # http (Traefik default entrypoint)
  routes:
    - match: Host(`passwds.local`)
      kind: Rule
      services:
        - name: vaultwarden
          port: 80
