apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: app-vaultwarden
spec:
  type: ClusterIP
  ports:
    - name: dashboard
      port: 80
      targetPort: 80
      protocol: TCP

