apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/controller/cert-manager
  prune: true
  wait: true
  dependsOn:
    - name: helm-repositories # Wait for the Helm repositories
    - name: traefik-infra  # Wait for MetalLB + its config
