apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 1h  # Check for new charts hourly
  path: ./helmrepositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
