apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-infra
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/controller/metallb
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: helm-repositories # Wait for the Helm repositories
