apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/config/metallb
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: metallb-infra
