apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: traefik
      version: "36.3.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace 

  values:
    deployment:
      kind: DaemonSet

    api:
      dashboard: true

    service:
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
      annotations:
        metallb.universe.tf/address-pool: traefik-ingress


    # Additional arguments as array
    additionalArguments:
      - "--entryPoints.dashboard.address=:9000/tcp"
      - "--entryPoints.dashboard.forwardedHeaders.insecure=true"
      - "--entryPoints.dashboard.proxyProtocol.insecure=true"

    ports:
      web:
        port: 80
        expose: true
        exposedPort: 80
      websecure:
        port: 443
        expose: true
        exposedPort: 443
      traefik:
        port: 8080
        expose: false
      # Add the dashboard port you defined
      dashboard:
        port: 9000
        expose: true
        exposedPort: 9000
