apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: app-vaultwarden
 name: pvc-vaultwarden
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
 storageClassName: longhorn
